baseURL = "https://arcotorrescacchi.github.io/"
languageCode = "it"
title = "A.S.D. Arcotorre Scacchi Chieri"
theme = "arcotorre-theme"

[params]
  description = "Circolo scacchistico di Chieri - Associazione Sportiva Dilettantistica"
  author = "Arcotorre Scacchi"
  address = "Via Papa Giovanni XXIII, 8 - Chieri (TO)"
  email = "info@arcotorre.it"
  lichessTeam = "https://lichess.org/team/arcotorre-scacchi"
  vesusOrg = "https://vesus.org"
  sponsor = "https://www.reveane.it"
  
[menu]
  [[menu.main]]
    identifier = "circolo"
    name = "Circolo"
    weight = 1
  [[menu.main]]
    parent = "circolo"
    name = "Struttura"
    url = "/circolo/struttura/"
    weight = 1
  [[menu.main]]
    parent = "circolo"
    name = "Calendario"
    url = "/circolo/calendario/"
    weight = 2
  [[menu.main]]
    parent = "circolo"
    name = "Orari"
    url = "/circolo/orari/"
    weight = 3
  [[menu.main]]
    parent = "circolo"
    name = "Iscrizione"
    url = "/circolo/iscrizione/"
    weight = 4
  [[menu.main]]
    parent = "circolo"
    name = "Biblioteca"
    url = "/circolo/biblioteca/"
    weight = 5	
  [[menu.main]]
    parent = "circolo"
    name = "Safeguarding"
    url = "/circolo/safeguarding/"
    weight = 6

  [[menu.main]]
    identifier = "tornei"
    name = "Tornei"
    weight = 2
  [[menu.main]]
    parent = "tornei"
    name = "Tornei e bandi"
    url = "/tornei/"
    weight = 1
  [[menu.main]]
    parent = "tornei"
    name = "C.I.S."
    url = "/tornei/cis/"
    weight = 2
  [[menu.main]]
    parent = "tornei"
    name = "Archivio risultati"
    url = "/tornei/archivio/"
    weight = 3

  [[menu.main]]
    identifier = "tecnica"
    name = "Sezione Tecnica"
    weight = 3
  [[menu.main]]
    parent = "tecnica"
    name = "Partite dei soci"
    url = "/tecnica/partite/"
    weight = 1
  [[menu.main]]
    parent = "tecnica"
    name = "Teoria"
    url = "/tecnica/teoria/"
    weight = 2
  [[menu.main]]
    parent = "tecnica"
    name = "Tattica"
    url = "/tecnica/tattica/"
    weight = 3
  [[menu.main]]
    parent = "tecnica"
    name = "Strategia"
    url = "/tecnica/strategia/"
    weight = 4
  [[menu.main]]
    parent = "tecnica"
    name = "Surfing on the net"
    url = "/tecnica/surfing/"
    weight = 5
  [[menu.main]]
    parent = "tecnica"
    name = "A te la mossa!"
    url = "/tecnica/atlm/"
    weight = 6

  [[menu.main]]
    identifier = "articoli"
    name = "Articoli"
    url = "/articoli/"
    weight = 4

  [[menu.main]]
    identifier = "galleria"
    name = "Galleria"
    url = "/galleria.html"
    weight = 5

  [[menu.main]]
    identifier = "contatti"
    name = "Contatti"
    weight = 6
  [[menu.main]]
    parent = "contatti"
    name = "Info e recapiti"
    url = "/contatti/"
    weight = 1
  [[menu.main]]
    parent = "contatti"
    name = "Links utili"
    url = "/links/"
    weight = 2

  [[menu.main]]
    identifier = "calendario"
    name = "ðŸ“… Calendario"
    url = "/circolo/calendario/"
    weight = 7
    [menu.main.params]
      class = "cta-button"

[[menu.main]]
  identifier = "quiz"
  name = "ðŸ§© Quiz"
  url = "/quiz/"
  weight = 9

[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
